name: Deploy to Firebase Hosting on push
on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Caching Gatsby
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
            .firebase
            node_modules
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-
      - run: npm i && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MAPLE_TERRACE_FULL_SITE }}'
          channelId: live
          projectId: maple-terrace-full-site
          target: ${{ fromJSON('["maple-terrace-full-site", "dev-maple-terrace-full-site"]')[github.ref != 'refs/heads/master'] }}
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

