name: Deploy to Firebase Hosting Preview on push
on:
  push:
    branches:
      - 'preview/**'
  workflow_dispatch:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Caching Gatsby
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
            .firebase
            node_modules
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-
      - name: Getting current branches
        id: current_branch
        run: |
          branch=${GITHUB_HEAD_REF}
          if [ -z "$branch" ]; then
            branch=${GITHUB_REF//refs\/heads\//}
          fi
          if [ -z "$branch" ]; then
            branch=$(git rev-parse --abbrev-ref HEAD)
          fi
          echo "##[set-output name=branch;]${branch}"
      - run: npm i && npm run build
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
          CI: true
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MAPLE_TERRACE }}'
          projectId: maple-terrace-6f38d
          target: dev-maple-terrace
          channelId: ${{ steps.current_branch.outputs.branch }}
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
